/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MacPoolReservation struct {
	HwAddress string `json:"hw_address,omitempty"`
	// As this is a synthesis of multiple reservations, it is the concatenation of all distinct comments over multiple lines.  To say this explicitly, if all reservations share the same comment, it will only appear once. 
	Comment string `json:"comment,omitempty"`
	Subnets []string `json:"subnets,omitempty"`
}
