/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BaseRecord struct {
	Id string `json:"id,omitempty"`
	// The transaction ID in which the record was created
	CreatedInTransaction int32 `json:"created_in_transaction,omitempty"`
	// The transaction ID in which the record was deleted
	DeletedInTransaction int32 `json:"deleted_in_transaction,omitempty"`
	// Freeform comment field. Markdown is recommended and may be rendered in certain situations in the UI.
	Comment string `json:"comment,omitempty"`
}
