/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LockEditableFields struct {
	Hostname string `json:"hostname,omitempty"`
	// Password to lock hostname with.
	LockPassword string `json:"lock_password,omitempty"`
	// Put your valuable credit card details here.
	Comment string `json:"comment,omitempty"`
}
