/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NewCircularRecord struct {
	Hostname string `json:"hostname,omitempty"`
	// IP address of the record. Can be any IP address within the subnet you wish to add the reservation to.
	Ip string `json:"ip,omitempty"`
	// Freeform field
	Comment string `json:"comment,omitempty"`
	// TTL of the record
	Ttl int32 `json:"ttl,omitempty"`
}
