/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NewMacPoolReservation struct {
	HwAddress string `json:"hw_address,omitempty"`
	// IP address of the record. Can be a subnet if it's for the pool
	Ip string `json:"ip,omitempty"`
	// Date after which reservation is not given leases. 
	Expiry string `json:"expiry,omitempty"`
	// Freeform field
	Comment string `json:"comment,omitempty"`
}
