/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CircularrecordsBulkBody struct {
	Records []AllOfcircularrecordsBulkBodyRecordsItems `json:"records,omitempty"`
	Comment string `json:"comment,omitempty"`
}
