/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AllOfcircularrecordsBulkBodyRecordsItems struct {
	Id string `json:"id,omitempty"`
	Action string `json:"action,omitempty"`
	// The hostname of the record. Validation is record type specific.
	Hostname string `json:"hostname"`
	// Freeform comment field. Markdown is recommended and may be rendered in certain situations in the UI.
	Comment string `json:"comment,omitempty"`
	// If the hostname is locked, an unlock is attempted with this password
	LockPassword string `json:"lock_password,omitempty"`
	// TTL of the record
	Ttl int32 `json:"ttl,omitempty"`
}
