/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Transaction struct {
	Id string `json:"id,omitempty"`
	Txid int32 `json:"txid,omitempty"`
	// The user who started the transaction
	Username string `json:"username,omitempty"`
	// The session user who started the transaction. Will be the same as username unless masquerading is occurring. Masquerading is not common. 
	UsernameSession string `json:"username_session,omitempty"`
	// Records created in this transaction. An update is a delete and a create
	RecordsCreated int32 `json:"records_created,omitempty"`
	// Records deleted in this transaction. An update is a delete and a create
	RecordsDeleted int32 `json:"records_deleted,omitempty"`
	At time.Time `json:"at,omitempty"`
}
