/*
 * Hydra IPAM
 *
 * A DNS/DHCP update API for University of Oxford, spec for phys0950
 *
 * API version: 1.55
 * Contact: networks@it.ox.ac.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Zone struct {
	SoaRefresh int32 `json:"soa_refresh,omitempty"`
	SoaRetryTime int32 `json:"soa_retry_time,omitempty"`
	SoaNxTtl int32 `json:"soa_nx_ttl,omitempty"`
	// Default TTL given to records in this zone. Can be overridden by the record.
	Ttl int32 `json:"ttl,omitempty"`
	Comment string `json:"comment,omitempty"`
	ValidTargetDomains []string `json:"valid_target_domains,omitempty"`
	ValidCircularRecordsSubnets []string `json:"valid_circular_records_subnets,omitempty"`
	ValidSupplementaryIpRecordsSubnets []string `json:"valid_supplementary_ip_records_subnets,omitempty"`
	Id string `json:"id,omitempty"`
	ZoneName string `json:"zone_name,omitempty"`
}
